"""
generator/assistant.py
----------------------
Assistant Agent — simulates the tool-using assistant.

All utterances (clarification questions, tool preambles, intermediate
summaries, final responses) are generated by the LLM. The plan's
per-step narrative fields (purpose, user_intent, assistant_intent) are
injected into every prompt so output is contextually grounded rather
than generic.

The structural parts of each turn (tool_calls list, role) remain
deterministic — only the natural-language content fields go to the LLM.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from synthetic_datagen.common.types import ClarificationStep
from synthetic_datagen.graph.registry import ToolRegistry
from synthetic_datagen.generator.executor import StepOutput
from synthetic_datagen.planner import StructuredConversationPlan


@dataclass
class AssistantTurn:
    """One assistant turn in the conversation."""
    role: str = "assistant"
    content: str = ""
    tool_calls: list[dict] | None = None


class AssistantAgent:
    """
    Simulates the tool-using assistant using an LLM for all utterances.

    The plan's per-step assistant_intent is the primary source of preamble
    text — the LLM is only called when that field is unavailable or generic.
    """

    def __init__(
        self,
        registry: ToolRegistry,
        llm_backend: Any,
        seed: int | None = None,
    ):
        self.registry = registry
        self.llm = llm_backend
        # seed retained for interface compatibility

    def ask_clarification(
        self,
        clarification: ClarificationStep,
        step_purpose: str | None = None,
    ) -> AssistantTurn:
        """Generate a clarification question grounded in the step's context."""
        if clarification.reason == "intent_ambiguity":
            prompt = (
                "You are an AI assistant asking a user to clarify what they want.\n\n"
                "The user sent an ambiguous opening message. Write one natural "
                "clarification question that encourages them to explain their goal. "
                "Be helpful and conversational. "
                "Return only the question text — no quotes, no labels."
            )
            content = self._call_llm(
                prompt,
                fallback="I'd be happy to help! Could you tell me a bit more about what you're looking to accomplish?",
            )
            return AssistantTurn(content=content)

        if clarification.missing_params:
            param_phrases = [p.replace("_", " ") for p in clarification.missing_params]
            listed = (
                param_phrases[0]
                if len(param_phrases) == 1
                else ", ".join(param_phrases[:-1]) + f" and {param_phrases[-1]}"
            )
            context = f"Task context: {step_purpose}\n" if step_purpose else ""
            prompt = (
                f"You are an AI assistant asking a user for missing information.\n\n"
                f"{context}"
                f"Missing information needed: {listed}\n\n"
                f"Write one natural, helpful question asking the user for this information. "
                f"If task context is provided, briefly reference it so the question "
                f"doesn't feel abrupt. "
                f"Return only the question text — no quotes, no labels."
            )
            content = self._call_llm(
                prompt,
                fallback=f"Could you provide your {listed}?",
            )
            return AssistantTurn(content=content)

        return AssistantTurn(content="Could you provide some additional details?")

    def emit_tool_call(
        self,
        endpoint_id: str,
        arguments: dict,
        preamble: str | None = None,
    ) -> AssistantTurn:
        """
        Generate an assistant turn that emits a tool call.

        preamble (plan_step.assistant_intent) is passed as a context hint
        to the LLM — it is never used verbatim because it contains plan
        language, not natural conversation language.
        """
        ep = self.registry.get_endpoint(endpoint_id)
        tool_name = ep.name if ep else endpoint_id.split("::")[-1]
        intent = ep.intent if ep else "retrieve"
        content = self._generate_preamble(tool_name, intent, context_hint=preamble)

        return AssistantTurn(
            content=content,
            tool_calls=[{"name": endpoint_id, "parameters": arguments}],
        )

    def interpret_tool_output(
        self,
        step: StepOutput,
        is_final: bool = False,
    ) -> AssistantTurn:
        """Generate an assistant turn that interprets tool output."""
        ep = self.registry.get_endpoint(step.endpoint_id)
        tool_name = ep.name if ep else step.endpoint_id.split("::")[-1]

        if is_final:
            content = self._generate_final_summary(tool_name, step.output)
        else:
            content = self._generate_intermediate_summary(tool_name, step.output)
        return AssistantTurn(content=content)

    def generate_final_response(
        self,
        plan: StructuredConversationPlan,
        all_steps: list[StepOutput],
    ) -> AssistantTurn:
        """Generate a grounded final response referencing actual tool output values."""
        steps_summary = []
        for step in all_steps:
            ep_label = step.endpoint_id.split("::")[-1].replace("_", " ")
            flat = self._flatten_output(step.output)
            if flat:
                fields_str = ", ".join(f"{k}: {v}" for k, v in list(flat.items())[:3])
                steps_summary.append(f"{ep_label} → {fields_str}")

        steps_text = (
            "\n".join(f"  - {s}" for s in steps_summary)
            if steps_summary else "  (task completed successfully)"
        )

        prompt = (
            f"You are an AI assistant who has just finished helping a user.\n\n"
            f"The user wanted: {plan.user_goal}\n"
            f"Domain: {plan.domain}\n\n"
            f"Here are the confirmed results from the tools you called:\n{steps_text}\n\n"
            f"Write a 2–3 sentence closing message that:\n"
            f"1. Tells the user what was actually accomplished based on the tool results above\n"
            f"2. Mentions 1–2 specific values from the results (like an ID, confirmation code, or price)\n"
            f"3. Invites any follow-up questions\n\n"
            f"CRITICAL: Only mention outcomes that are confirmed by the tool results listed above. "
            f"Do NOT claim features were added (like attendees, locations, attachments) if those "
            f"fields do not appear in the tool results. Do NOT invent booking references or IDs "
            f"that are not in the results.\n\n"
            f"Return only the message text — no quotes, no labels."
        )
        content = self._call_llm(
            prompt,
            fallback="I've completed all the steps successfully. Let me know if you need anything else.",
        )

        # Grounding check — rewrite if the response overclaims relative to tool outputs
        content = self._ground_check_response(content, steps_text, plan.user_goal)
        return AssistantTurn(content=content)

    def _ground_check_response(
        self,
        response: str,
        tool_results_summary: str,
        user_goal: str,
    ) -> str:
        """
        Verify the response only claims outcomes present in the tool results.

        If the LLM detects overclaiming (e.g. "Italian restaurant booked" when
        the search returned no Italian options), it rewrites the response to be
        accurate. Returns the original if no issues are found or on any error.
        """
        prompt = (
            f"You are reviewing an AI assistant's closing message for factual accuracy.\n\n"
            f"User's goal: {user_goal}\n\n"
            f"Actual tool results:\n{tool_results_summary}\n\n"
            f"Assistant's closing message:\n\"{response}\"\n\n"
            f"Does the closing message claim anything that is NOT confirmed by the tool results? "
            f"For example: claiming a specific cuisine was booked when results show a different cuisine, "
            f"mentioning attendees that weren't in the tool output, or referencing IDs not in results.\n\n"
            f"If the message is accurate: reply with exactly ACCURATE\n"
            f"If it overclaims: reply with REWRITE: followed by a corrected 2–3 sentence message "
            f"that only states what the tool results actually confirm.\n"
            f"No other text."
        )
        try:
            answer = self._call_llm(prompt, fallback="ACCURATE")
            if answer.upper().startswith("REWRITE:"):
                rewritten = answer.split(":", 1)[-1].strip().strip('"').strip("'")
                return rewritten if rewritten else response
            return response
        except Exception:
            return response

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_preamble(self, tool_name: str, intent: str, context_hint: str | None = None) -> str:
        """Generate a short natural-language preamble before a tool call."""
        tool_label = tool_name.replace("_", " ")
        hint_line = f"What you are about to do: {context_hint}\n" if context_hint else ""
        prompt = (
            f"You are an AI assistant about to call a tool on behalf of a user.\n"
            f"Tool: {tool_label}\n"
            f"Action type: {intent}\n"
            f"{hint_line}\n"
            f"Write one short, natural sentence telling the user what you are about to do. "
            f"Sound like a helpful human — not a system log or a plan description. "
            f"Good examples: 'Let me search for available flights.', "
            f"'I'll go ahead and book that for you.', 'Let me pull up your inbox.'\n"
            f"Return only the sentence — no quotes, no labels."
        )
        return self._call_llm(
            prompt,
            fallback="Let me take care of that for you.",
        )

    def _flatten_output(self, output: dict) -> dict:
        """Flatten one level of nested dicts and filter structural fields."""
        skip = {"status", "ok", "result", "success", "message", "error", "code"}
        flat: dict = {}
        for k, v in output.items():
            if isinstance(v, dict):
                for nk, nv in v.items():
                    if nk not in skip and not isinstance(nv, (dict, list)):
                        flat[nk] = nv
            elif not isinstance(v, list) and k not in skip:
                flat[k] = v
        return flat

    def _generate_intermediate_summary(self, tool_name: str, output: dict) -> str:
        """Generate a brief acknowledgement of an intermediate tool result."""
        meaningful = {
            k: v for k, v in output.items()
            if k not in {"status", "ok", "result", "success", "message", "error", "code"}
            and not isinstance(v, (dict, list))
        }
        fields_str = (
            json.dumps(dict(list(meaningful.items())[:2]))
            if meaningful else "{}"
        )
        tool_label = tool_name.replace("_", " ")
        prompt = (
            f"You are an AI assistant who just received a tool result.\n"
            f"Tool: {tool_label}\n"
            f"Key result values: {fields_str}\n\n"
            f"Write one short sentence acknowledging the result. Reference at most "
            f"one specific value from the result. Do not start with 'I'. "
            f"Return only the sentence — no quotes, no labels."
        )
        return self._call_llm(prompt, fallback="Done.")

    def _generate_final_summary(self, tool_name: str, output: dict) -> str:
        """Generate a summary sentence for the last tool step."""
        tool_label = tool_name.replace("_", " ")
        prompt = (
            f"You are an AI assistant summarising the final step of a task.\n"
            f"Tool used: {tool_label}\n"
            f"Result: {json.dumps(output)[:300]}\n\n"
            f"Write one sentence confirming the step completed and highlighting "
            f"the key result. Return only the sentence — no quotes, no labels."
        )
        return self._call_llm(
            prompt,
            fallback=f"The {tool_label} step completed successfully.",
        )

    def _call_llm(self, prompt: str, fallback: str = "") -> str:
        """Call the LLM backend and return clean text. Returns fallback on any error."""
        try:
            result = self.llm.complete(prompt).strip().strip('"').strip("'").strip()
            return result if result else fallback
        except Exception:
            return fallback
