"""
generator/user_proxy.py
-----------------------
User-Proxy Agent — simulates the human side of the conversation.

All user utterances are generated by the LLM using the rich narrative
context already present in the StructuredConversationPlan (domain,
user_goal, conversation_style, style_notes, per-step user_intent).

Canonical parameter values remain deterministic so they flow correctly
into the executor's argument resolution (Priority 1 in the 4-step
precedence policy). Only the natural-language sentences wrapping those
values are LLM-generated.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from synthetic_datagen.common.types import ClarificationStep
from synthetic_datagen.graph.registry import ToolRegistry
from synthetic_datagen.planner import StructuredConversationPlan


@dataclass
class UserTurn:
    """One user turn in the conversation."""
    role: str = "user"
    content: str = ""
    resolved_params: dict[str, Any] = field(default_factory=dict)


class UserProxyAgent:
    """
    Simulates user utterances using an LLM for all natural language generation.

    The plan's narrative fields (domain, user_goal, conversation_style,
    style_notes) ground every prompt so the generated text is coherent with
    the conversation's intent and tone.
    """

    def __init__(
        self,
        registry: ToolRegistry,
        llm_backend: Any,
        seed: int | None = None,
    ):
        self.registry = registry
        self.llm = llm_backend
        # seed retained for interface compatibility but not used —
        # randomness comes from the LLM's temperature, not rng.choice

    def generate_initial_request(self, plan: StructuredConversationPlan) -> UserTurn:
        """Generate the opening user message grounded in the plan's narrative."""
        prompt = (
            f"You are simulating a user starting a conversation with an AI assistant.\n\n"
            f"Domain: {plan.domain}\n"
            f"Conversation style: {plan.conversation_style}\n"
            f"Style guidance: {plan.style_notes}\n"
            f"User's goal: {plan.user_goal}\n\n"
            f"Write exactly one opening message the user would send to begin this "
            f"conversation. Match the conversation style precisely. Do not mention "
            f"specific API or tool names. Return only the message text — no quotes, "
            f"no labels, no explanation."
        )
        content = self._call_llm(prompt, fallback=f"I need help with: {plan.user_goal}")
        return UserTurn(content=content)

    def answer_clarification(
        self,
        clarification: ClarificationStep,
        plan: StructuredConversationPlan,
        original_request: str | None = None,
        accumulated_fields: dict | None = None,
    ) -> UserTurn:
        """
        Generate a user response to a clarification question.

        Returns a UserTurn with both the natural-language content AND
        resolved_params — the machine-readable values that back the utterance.
        These are passed to executor.execute_step(user_inputs=...) so tool
        arguments are consistent with what the user said.

        original_request:   the user's opening message, so the answer stays
                            coherent with what was already said.
        accumulated_fields: real values from prior tool outputs — ID-type
                            params are resolved from here first before asking
                            the LLM to invent a value.
        """
        prior_line = (
            f"The user's opening message was: \"{original_request}\"\n"
            if original_request else ""
        )
        accumulated = accumulated_fields or {}

        if clarification.reason == "intent_ambiguity":
            prompt = (
                f"You are simulating a user clarifying their request to an AI assistant.\n\n"
                f"Domain: {plan.domain}\n"
                f"Conversation style: {plan.conversation_style}\n"
                f"{prior_line}"
                f"The user's actual goal: {plan.user_goal}\n\n"
                f"The assistant asked for clarification about what the user wants. "
                f"Write one natural response that clarifies the user's intent, "
                f"building on what they already said. Do not repeat information "
                f"already provided. Return only the response text — no quotes, no labels."
            )
            content = self._call_llm(
                prompt,
                fallback=f"I want to accomplish: {plan.user_goal}",
            )
            return UserTurn(content=content)

        if clarification.missing_params:
            resolved: dict[str, Any] = {}
            phrases: list[str] = []

            for param in clarification.missing_params:
                phrase, value = self._resolve_param(param, plan, accumulated)
                phrases.append(phrase)
                if value is not None:
                    resolved[param] = value

            if phrases:
                joined = "; ".join(phrases)
                prompt = (
                    f"You are simulating a user answering a follow-up question from an AI assistant.\n\n"
                    f"Domain: {plan.domain}\n"
                    f"Conversation style: {plan.conversation_style}\n"
                    f"{prior_line}"
                    f"The user needs to provide: {joined}\n\n"
                    f"Write one natural sentence that provides this information, "
                    f"consistent with the user's goal and what they already said. "
                    f"Return only the sentence — no quotes, no labels."
                )
                content = self._call_llm(prompt, fallback=joined)
            else:
                content = "Here is the additional information you need."
            return UserTurn(content=content, resolved_params=resolved)

        return UserTurn(content="Here is the additional information you need.")

    def generate_confirmation(self, plan: StructuredConversationPlan) -> UserTurn:
        """Generate a brief user confirmation after the assistant completes a task."""
        prompt = (
            f"You are simulating a user confirming an AI assistant's completed response.\n"
            f"Conversation style: {plan.conversation_style}\n\n"
            f"Write one brief, natural confirmation or thank-you message (1 sentence). "
            f"Match the conversation style. Return only the message text — no quotes, "
            f"no labels."
        )
        content = self._call_llm(prompt, fallback="That looks great, thank you!")
        return UserTurn(content=content)

    def _resolve_param(
        self,
        param_name: str,
        plan: StructuredConversationPlan,
        accumulated_fields: dict,
    ) -> tuple[str, Any]:
        """
        Resolve a missing parameter to (phrase, typed_value).

        Priority:
          1. accumulated_fields — real value from a prior tool output.
             ID-type params (hotel_id, flight_id, etc.) must come from here
             so the conversation chains correctly.
          2. LLM — generate a contextually appropriate value given the user's
             goal and domain. Returns JSON {value, phrase} in one call.
        """
        readable = param_name.replace("_", " ")

        # Priority 1: real value from a prior step output
        if param_name in accumulated_fields:
            value = accumulated_fields[param_name]
            return f"the {readable} is {value}", value

        # Priority 2: LLM generates a realistic value and phrase together
        prompt = (
            f"A user is answering a clarification question from an AI assistant.\n"
            f"User's goal: {plan.user_goal}\n"
            f"Domain: {plan.domain}\n"
            f"The assistant needs the user to provide: {readable}\n\n"
            f"Return a JSON object with exactly two fields:\n"
            f"  \"value\": a realistic, contextually appropriate value for '{readable}'\n"
            f"  \"phrase\": one natural phrase the user says to provide it\n\n"
            f"Example: {{\"value\": \"Paris\", \"phrase\": \"I'm headed to Paris\"}}\n"
            f"Return only valid JSON — no explanation, no markdown fences."
        )
        raw = self._call_llm(prompt, fallback="")
        try:
            raw = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
            data = json.loads(raw)
            value = data.get("value", readable)
            phrase = data.get("phrase", f"the {readable} is {value}")
            return phrase, value
        except Exception:
            return f"my {readable}", readable

    def _call_llm(self, prompt: str, fallback: str = "") -> str:
        """Call the LLM backend and return clean text. Returns fallback on any error."""
        try:
            result = self.llm.complete(prompt).strip().strip('"').strip("'").strip()
            return result if result else fallback
        except Exception:
            return fallback
